# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: true
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
script:
    - julia -e 'using Pkg;
                if VERSION >= v"1.1.0";
                  Registry.add(Registry.RegistrySpec(url = "https://github.com/JuliaRegistries/General.git"));
                  Registry.add(Registry.RegistrySpec(url = "https://github.com/BioJulia/BioJuliaRegistry.git"));
                  Pkg.build(verbose = true);
                else;
                  Pkg.build();
                end;
                Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'