name = "PhyloModels"
uuid = "6465ae08-de3a-5dbe-bda8-3920f6a01ab7"
authors = ["justin <justinangevaare@gmail.com>"]
version = "0.3.0"

[deps]
GeneticBitArrays = "5d6f8c34-7f74-4dab-a49b-48b3414fbfce"
PhyloTrees = "4c47b132-0681-5a5d-b498-3afcf53fd314"
SubstitutionModels = "8365b1bb-bd83-58ee-a267-f2965fc81c73"

[compat]
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
