name = "PhyloModels"
uuid = "6465ae08-de3a-5dbe-bda8-3920f6a01ab7"
authors = ["Justin Angevaare <justinangevaare@gmail.com>"]
version = "0.3.4"

[deps]
GeneticBitArrays = "5d6f8c34-7f74-4dab-a49b-48b3414fbfce"
PhyloTrees = "4c47b132-0681-5a5d-b498-3afcf53fd314"
SubstitutionModels = "8365b1bb-bd83-58ee-a267-f2965fc81c73"

[compat]
GeneticBitArrays = "0.2.1, 0.3"
PhyloTrees = "0.10, 0.11"
SubstitutionModels = "0.4, 0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
