name: TagBot
on:
  schedule:
    - cron: 0 * * * *
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog: |
            ## {{ package }} {{ version }}
            
            {% if custom %}
            {{ custom }}
            {% endif %}
            
            {% if previous_release %}
            [Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}
